config/routes.rb
Rails.application.routes.draw do
  #get 'search/results'
  # get 'country/index'
  # get 'country/show'
  # get 'university/index'
  # get 'university/show'
  get 'about/home'

  resources :university , only:[:index,:show]
  resources :country , only:[:index,:show]

  resources :search ,only:[:results] do
    collection do
      get 'results'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'about#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :universities

    validates :name , presence: true

    paginates_per 10
end

app/models/university.rb
class University < ApplicationRecord
  belongs_to :country
  has_many :uniwebs
  has_many :websites , through: :uniwebs

  validates :name , presence: true
  validates :alpha_code , presence: true
  validates :state_province , presence: true
  validates :dean , presence: true

  paginates_per 10

end

app/models/uniweb.rb
class Uniweb < ApplicationRecord
  belongs_to :website
  belongs_to :university
end

app/models/website.rb
class Website < ApplicationRecord
    has_one :uniweb
    has_one :university , through: :uniweb
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def home
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/country_controller.rb
class CountryController < ApplicationController
  def index
    @countries = Country.all.order(:name).page params[:page]
  end

  def show
    @country = Country.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def results
    
    if params[:query_country][:country_id].empty?
      @universities = University.where('name LIKE ?', "%#{params[:q]}%")
    else
      c = Country.find(params[:query_country][:country_id])
      @universities = c.universities.where('name LIKE ?', "%#{params[:q]}%")
  end
  end
end

app/controllers/university_controller.rb
class UniversityController < ApplicationController
  def index
    @univerities = University.all.page params[:page]
  end

  def show
    @u = University.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/university_helper.rb
module UniversityHelper
end

app/views/about/home.html.erb
<h1>About Us</h1>
<p>This is a project about Universities around the World</p>

<p>Dean information is from faker data</p>

<p>Their is almost 10,000 university's</p>

<p>The ERD diagram gives information about table relationships</p>


<p>Used Dataset from this<a href="https://raw.githubusercontent.com/Hipo/university-domains-list/master/world_universities_and_domains.json?fbclid=IwAR10LKFrfohIYNzvVV9Na4PPcvg0DE01GhTQ-FbinhBlM98hf_BDmZUauBY"> Github Link </a></p>

<p>ERD</p>
<img src="/assets⁩/erdmodel.jpg" alt="Database" height="500" width="700">

app/views/country/index.html.erb
<h1>Countries</h1>

<%= paginate @countries%>

<% @countries.each do |c|%>

<p><%=c.name%> <%=link_to 'See Universities', c %></p>

<%end%>

app/views/country/show.html.erb
<h1><%= @country.name%></h1>
<p><%= @country.universities.count %> universities in <%=@country.name%></p>

<% @country.universities.each do |u|%>

    <p><%= u.name %> , <%=  link_to 'See University', u %></p>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Introproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li><%= link_to 'About Us', root_path %></li>
      <li><%= link_to 'Universities', university_index_path %></li>
      <li><%= link_to 'Countries', country_index_path %></li>
    </ul>
    <div id = "search">
          <%= form_tag(results_search_index_path, method: "get") do %>
            <%= label_tag(:q, "Search:") %>
            <%= text_field_tag(:q) %>
            <%= collection_select(:query_country , :country_id , Country.all.order(:name), :id ,:name,{:include_blank => 'University Name'})%>
            <%= submit_tag("Search") %>
          <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/search/results.html.erb
<h1>Search Results</h1>
<% if @universities.count == 1 %>
  <p><%= @universities.count %> result found.</p>
  <%else%>
  <p><%= @universities.count %> results found.</p>
<% end %>


<% @universities.each do |u| %>

    <p><%= link_to "#{u.name}",u %> -  <%= u.country.name %></p>
    
    
<% end %>

app/views/university/index.html.erb
<h1>Universities</h1>

<%= paginate @univerities%>

<% @univerities.each do |u| %>

    <p><%= link_to "#{u.name}",u %> -  <%= u.country.name %></p>
    
    
<% end %>

app/views/university/show.html.erb
<h1><%= @u.name %></h1>
<p><b> University Details</b></p>

<p>University Name : <%= @u.name %></p>
<p>Alpha Code : <%= @u.alpha_code %></p>
<p>Dean : <%= @u.dean  %></p>
<p>State/Province : <%= @u.state_province %></p>
<p>Country : <%= @u.country.name %></p>

<p><b>University Websites:</b></p>
<% @u.websites.each do |w| %>
    <p><a href="<%=w.webpage%>"><%=w.webpage%></a></p>
<%end%>